In [1]:
import pandas as pd

In [3]:
db = pd.read_csv("C:\\Users\\LOQ\\Downloads\\Iris.csv")

In [4]:
db

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
from sklearn import preprocessing

In [6]:
db.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  NaN            4.7           3.2            1.3           0.2  Iris-setosa
3  NaN            4.6           3.1            1.5           0.2  Iris-setosa
4  NaN            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
min_max_scaler=preprocessing.MinMaxScaler()

In [9]:
min_max_scaler

MinMaxScaler()

In [10]:
x = db.iloc[:,:4]

In [11]:
x

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0      1.0            5.1           3.5            1.4
1      2.0            4.9           3.0            1.4
2      NaN            4.7           3.2            1.3
3      NaN            4.6           3.1            1.5
4      NaN            5.0           3.6            1.4
..     ...            ...           ...            ...
145  146.0            6.7           3.0            5.2
146  147.0            6.3           2.5            5.0
147  148.0            6.5           3.0            5.2
148  149.0            6.2           3.4            5.4
149  150.0            5.9           3.0            5.1

[150 rows x 4 columns]

In [12]:
x_scaled = min_max_scaler.fit_transform(x)

In [13]:
x_scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661],
       [       nan, 0.11111111, 0.5       , 0.05084746],
       [       nan, 0.08333333, 0.45833333, 0.08474576],
       [       nan, 0.19444444, 0.66666667, 0.06779661],
       [       nan, 0.30555556, 0.79166667, 0.11864407],
       [       nan, 0.08333333, 0.58333333, 0.06779661],
       [       nan, 0.19444444, 0.58333333, 0.08474576],
       [0.05369128, 0.02777778, 0.375     , 0.06779661],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661],
       [0.08724832, 0.        , 0.41666667, 0.01694915],
       [0.09395973, 0.41666667, 0.83333333, 0.03389831],
       [0.10067114, 0.38888889, 1.        , 0.08474576],
       [0.10738255, 0.30555556, 0.79166667, 0.05084746],
       [0.11409396, 0.22222222, 0.625     , 0.06779661],
       [0.12080537, 0.38888889, 0.75      , 0.11864407],
       [0.12751678, 0.22222222, 0.75      , 0.08474576],
       [0.13422819, 0.30555556, 0.58333333, 0.11864407],
       [0.1409396 , 0.22222222, 0.70833333, 0.08474576],
       [0.14765101, 0.08333333, 0.66666667, 0.        ],
       [0.15436242, 0.22222222, 0.54166667, 0.11864407],
       [0.16107383, 0.13888889, 0.58333333, 0.15254237],
       [0.16778523, 0.19444444, 0.41666667, 0.10169492],
       [0.17449664, 0.19444444, 0.58333333, 0.10169492],
       [0.18120805, 0.25      , 0.625     , 0.08474576],
       [0.18791946, 0.25      , 0.58333333, 0.06779661],
       [0.19463087, 0.11111111, 0.5       , 0.10169492],
       [0.20134228, 0.13888889, 0.45833333, 0.10169492],
       [0.20805369, 0.30555556, 0.58333333, 0.08474576],
       [0.2147651 , 0.25      , 0.875     , 0.08474576],
       [0.22147651, 0.33333333, 0.91666667, 0.06779661],
       [0.22818792, 0.16666667, 0.45833333, 0.08474576],
       [0.23489933, 0.19444444, 0.5       , 0.03389831],
       [0.24161074, 0.33333333, 0.625     , 0.05084746],
       [0.24832215, 0.16666667, 0.45833333, 0.08474576],
       [0.25503356, 0.02777778, 0.41666667, 0.05084746],
       [0.26174497, 0.22222222, 0.58333333, 0.08474576],
       [0.26845638, 0.19444444, 0.625     , 0.05084746],
       [0.27516779, 0.05555556, 0.125     , 0.05084746],
       [0.28187919, 0.02777778, 0.5       , 0.05084746],
       [0.2885906 , 0.19444444, 0.625     , 0.10169492],
       [0.29530201, 0.22222222, 0.75      , 0.15254237],
       [0.30201342, 0.13888889, 0.41666667, 0.06779661],
       [0.30872483, 0.22222222, 0.75      , 0.10169492],
       [0.31543624, 0.08333333, 0.5       , 0.06779661],
       [0.32214765, 0.27777778, 0.70833333, 0.08474576],
       [0.32885906, 0.19444444, 0.54166667, 0.06779661],
       [0.33557047, 0.75      , 0.5       , 0.62711864],
       [0.34228188, 0.58333333, 0.5       , 0.59322034],
       [0.34899329, 0.72222222, 0.45833333, 0.66101695],
       [0.3557047 , 0.33333333, 0.125     , 0.50847458],
       [0.36241611, 0.61111111, 0.33333333, 0.61016949],
       [0.36912752, 0.38888889, 0.33333333, 0.59322034],
       [0.37583893, 0.55555556, 0.54166667, 0.62711864],
       [0.38255034, 0.16666667, 0.16666667, 0.38983051],
       [0.38926174, 0.63888889, 0.375     , 0.61016949],
       [0.39597315, 0.25      , 0.29166667, 0.49152542],
       [0.40268456, 0.19444444, 0.        , 0.42372881],
       [0.40939597, 0.44444444, 0.41666667, 0.54237288],
       [0.41610738, 0.47222222, 0.08333333, 0.50847458],
       [0.42281879, 0.5       , 0.375     , 0.62711864],
       [0.4295302 , 0.36111111, 0.375     , 0.44067797],
       [0.43624161, 0.66666667, 0.45833333, 0.57627119],
       [0.44295302, 0.36111111, 0.41666667, 0.59322034],
       [0.44966443, 0.41666667, 0.29166667, 0.52542373],
       [0.45637584, 0.52777778, 0.08333333, 0.59322034],
       [0.46308725, 0.36111111, 0.20833333, 0.49152542],
       [0.46979866, 0.44444444, 0.5       , 0.6440678 ],
       [0.47651007, 0.5       , 0.33333333, 0.50847458],
       [0.48322148, 0.55555556, 0.20833333, 0.66101695],
       [0.48993289, 0.5       , 0.33333333, 0.62711864],
       [0.4966443 , 0.58333333, 0.375     , 0.55932203],
       [0.5033557 , 0.63888889, 0.41666667, 0.57627119],
       [0.51006711, 0.69444444, 0.33333333, 0.6440678 ],
       [0.51677852, 0.66666667, 0.41666667, 0.6779661 ],
       [0.52348993, 0.47222222, 0.375     , 0.59322034],
       [0.53020134, 0.38888889, 0.25      , 0.42372881],
       [0.53691275, 0.33333333, 0.16666667, 0.47457627],
       [0.54362416, 0.33333333, 0.16666667, 0.45762712],
       [0.55033557, 0.41666667, 0.29166667, 0.49152542],
       [0.55704698, 0.47222222, 0.29166667, 0.69491525],
       [0.56375839, 0.30555556, 0.41666667, 0.59322034],
       [0.5704698 , 0.47222222, 0.58333333, 0.59322034],
       [0.57718121, 0.66666667, 0.45833333, 0.62711864],
       [0.58389262, 0.55555556, 0.125     , 0.57627119],
       [0.59060403, 0.36111111, 0.41666667, 0.52542373],
       [0.59731544, 0.33333333, 0.20833333, 0.50847458],
       [0.60402685, 0.33333333, 0.25      , 0.57627119],
       [0.61073826, 0.5       , 0.41666667, 0.61016949],
       [0.61744966, 0.41666667, 0.25      , 0.50847458],
       [0.62416107, 0.19444444, 0.125     , 0.38983051],
       [0.63087248, 0.36111111, 0.29166667, 0.54237288],
       [0.63758389, 0.38888889, 0.41666667, 0.54237288],
       [0.6442953 , 0.38888889, 0.375     , 0.54237288],
       [0.65100671, 0.52777778, 0.375     , 0.55932203],
       [0.65771812, 0.22222222, 0.20833333, 0.33898305],
       [0.66442953, 0.38888889, 0.33333333, 0.52542373],
       [0.67114094, 0.55555556, 0.54166667, 0.84745763],
       [0.67785235, 0.41666667, 0.29166667, 0.69491525],
       [0.68456376, 0.77777778, 0.41666667, 0.83050847],
       [0.69127517, 0.55555556, 0.375     , 0.77966102],
       [0.69798658, 0.61111111, 0.41666667, 0.81355932],
       [0.70469799, 0.91666667, 0.41666667, 0.94915254],
       [0.7114094 , 0.16666667, 0.20833333, 0.59322034],
       [0.71812081, 0.83333333, 0.375     , 0.89830508],
       [0.72483221, 0.66666667, 0.20833333, 0.81355932],
       [0.73154362, 0.80555556, 0.66666667, 0.86440678],
       [0.73825503, 0.61111111, 0.5       , 0.69491525],
       [0.74496644, 0.58333333, 0.29166667, 0.72881356],
       [0.75167785, 0.69444444, 0.41666667, 0.76271186],
       [0.75838926, 0.38888889, 0.20833333, 0.6779661 ],
       [0.76510067, 0.41666667, 0.33333333, 0.69491525],
       [0.77181208, 0.58333333, 0.5       , 0.72881356],
       [0.77852349, 0.61111111, 0.41666667, 0.76271186],
       [0.7852349 , 0.94444444, 0.75      , 0.96610169],
       [0.79194631, 0.94444444, 0.25      , 1.        ],
       [0.79865772, 0.47222222, 0.08333333, 0.6779661 ],
       [0.80536913, 0.72222222, 0.5       , 0.79661017],
       [0.81208054, 0.36111111, 0.33333333, 0.66101695],
       [0.81879195, 0.94444444, 0.33333333, 0.96610169],
       [0.82550336, 0.55555556, 0.29166667, 0.66101695],
       [0.83221477, 0.66666667, 0.54166667, 0.79661017],
       [0.83892617, 0.80555556, 0.5       , 0.84745763],
       [0.84563758, 0.52777778, 0.33333333, 0.6440678 ],
       [0.85234899, 0.5       , 0.41666667, 0.66101695],
       [0.8590604 , 0.58333333, 0.33333333, 0.77966102],
       [0.86577181, 0.80555556, 0.41666667, 0.81355932],
       [0.87248322, 0.86111111, 0.33333333, 0.86440678],
       [0.87919463, 1.        , 0.75      , 0.91525424],
       [0.88590604, 0.58333333, 0.33333333, 0.77966102],
       [0.89261745, 0.55555556, 0.33333333, 0.69491525],
       [0.89932886, 0.5       , 0.25      , 0.77966102],
       [0.90604027, 0.94444444, 0.41666667, 0.86440678],
       [0.91275168, 0.55555556, 0.58333333, 0.77966102],
       [0.91946309, 0.58333333, 0.45833333, 0.76271186],
       [0.9261745 , 0.47222222, 0.41666667, 0.6440678 ],
       [0.93288591, 0.72222222, 0.45833333, 0.74576271],
       [0.93959732, 0.66666667, 0.45833333, 0.77966102],
       [0.94630872, 0.72222222, 0.45833333, 0.69491525],
       [0.95302013, 0.41666667, 0.29166667, 0.69491525],
       [0.95973154, 0.69444444, 0.5       , 0.83050847],
       [0.96644295, 0.66666667, 0.54166667, 0.79661017],
       [0.97315436, 0.66666667, 0.41666667, 0.71186441],
       [0.97986577, 0.55555556, 0.20833333, 0.6779661 ],
       [0.98657718, 0.61111111, 0.41666667, 0.71186441],
       [0.99328859, 0.52777778, 0.58333333, 0.74576271],
       [1.        , 0.44444444, 0.41666667, 0.69491525]])

In [14]:
db_normalized = pd.DataFrame(x_scaled)

In [15]:
db_normalized

            0         1         2         3
0    0.000000  0.222222  0.625000  0.067797
1    0.006711  0.166667  0.416667  0.067797
2         NaN  0.111111  0.500000  0.050847
3         NaN  0.083333  0.458333  0.084746
4         NaN  0.194444  0.666667  0.067797
..        ...       ...       ...       ...
145  0.973154  0.666667  0.416667  0.711864
146  0.979866  0.555556  0.208333  0.677966
147  0.986577  0.611111  0.416667  0.711864
148  0.993289  0.527778  0.583333  0.745763
149  1.000000  0.444444  0.416667  0.694915

[150 rows x 4 columns]

In [17]:
db['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [18]:
label_encoder = preprocessing.LabelEncoder()

In [19]:
label_encoder

LabelEncoder()

In [20]:
db['Species']=label_encoder.fit_transform(db['Species'])

In [21]:
db['Species'].unique()

array([0, 1, 2])

In [26]:
one_hot_db = pd.get_dummies(db,columns=["Species"],prefix='Species',drop_first=True)

In [27]:
one_hot_db

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_1,Species_2
0,1.0,5.1,3.5,1.4,0.2,False,False
1,2.0,4.9,3.0,1.4,0.2,False,False
2,NaN,4.7,3.2,1.3,0.2,False,False
3,NaN,4.6,3.1,1.5,0.2,False,False
4,NaN,5.0,3.6,1.4,0.2,False,False
...,...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,False,True
146,147.0,6.3,2.5,5.0,1.9,False,True
147,148.0,6.5,3.0,5.2,2.0,False,True
148,149.0,6.2,3.4,5.4,2.3,False,True
149,150.0,5.9,3.0,5.1,1.8,False,True